### ISSUE TITLE
screen saver never exits to allow user to use the board

### ISSUE THREAD

**Issue by bmorwood** [smashreality/blumination#8]
I noticed that the screen saver is initiated but never quits once a user interacts with the buttons, I noticed the buttons can be clicked but the screen saver keeps playing so the button that is pressed shows for a second and the animation continues. I can't recreate how this happens, it seems very random... the most basic recreation is to start the peg board by plugging the power in, waiting for the light test sequence and then touch a button and it fights with the screen saver, try the same test and it might be fine, very odd.

**Comment by bmorwood** [comment]
We need this fixed by the weekend as those are big days with the most people out of town.

**Comment by Naismith** [comment]
should be resolved now.
